title: Harjot Kaur # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Product and Analytics specialist with 10+ years of experience in product analytics, revenue management and new product development across Retail, Telecom, Energy and Mining sectors.
  <br><br>
  I operate at the intersection of Analytics, Product Management and Revenue management.  

 
  <br><br>
  A marathoner, mountaineer and an avid reader! 
  <br><br>
  <a href="https://www.linkedin.com/in/harjot-kaur-99792118/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/harjotdadhwal">View My LinkedIn Profile</a>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

  
 
